# Initial cache for the first MyLite MariaDB embedded-library baseline.
#
# Keep this file limited to reproducibility settings and options required by
# the intentionally partial MariaDB submodule import. The build wrapper handles
# packaging-only archive stripping after the normal MariaDB build.

set(CMAKE_BUILD_TYPE "MinSizeRel" CACHE STRING "MariaDB baseline build type" FORCE)

set(UPDATE_SUBMODULES OFF CACHE BOOL "Do not fetch MariaDB submodules during configure" FORCE)
set(WITH_EMBEDDED_SERVER ON CACHE BOOL "Build MariaDB's embedded server library" FORCE)
set(WITH_UNIT_TESTS OFF CACHE BOOL "Skip MariaDB upstream unit-test targets in the baseline" FORCE)
set(WITH_SSL "system" CACHE STRING "Use the host OpenSSL installation" FORCE)
set(WITH_ZLIB "bundled" CACHE STRING "Use MariaDB's bundled zlib for reproducible include paths" FORCE)

# These components require optional submodule payloads that are intentionally not
# included in the initial import.
set(WITH_WSREP OFF CACHE BOOL "Disable Galera/wsrep support for the embedded baseline" FORCE)
set(PLUGIN_S3 "NO" CACHE STRING "Disable Aria S3 support for the embedded baseline" FORCE)
set(PLUGIN_PERFSCHEMA "NO" CACHE STRING "Disable Performance Schema in the embedded baseline" FORCE)
set(PLUGIN_FEEDBACK "NO" CACHE STRING "Disable MariaDB feedback reporting in the embedded baseline" FORCE)
set(PLUGIN_USER_VARIABLES "NO" CACHE STRING "Disable user-variable diagnostics in the embedded baseline" FORCE)
set(PLUGIN_AUTH_SOCKET "NO" CACHE STRING "Disable Unix socket server authentication in the embedded baseline" FORCE)
set(ENABLED_PROFILING OFF CACHE BOOL "Disable statement profiling in the embedded baseline" FORCE)
set(MYLITE_WITH_BINLOG_CORE OFF CACHE BOOL "Disable binary log runtime core in the embedded baseline" FORCE)
set(MYLITE_WITH_BINLOG_REPLAY OFF CACHE BOOL "Disable SQL BINLOG statement replay in the embedded baseline" FORCE)
set(MYLITE_WITH_LOG_EVENT_SERVER OFF CACHE BOOL "Disable server binary-log event writers in the embedded baseline" FORCE)
set(MYLITE_WITH_LOG_EVENT_PARSING OFF CACHE BOOL "Disable binary-log event parsing in the embedded baseline" FORCE)
set(MYLITE_WITH_GTID_STATE OFF CACHE BOOL "Disable replication GTID state runtime in the embedded baseline" FORCE)
set(MYLITE_WITH_GTID_INDEX OFF CACHE BOOL "Disable binary-log GTID index runtime in the embedded baseline" FORCE)
set(MYLITE_WITH_SQL_HANDLER OFF CACHE BOOL "Disable SQL HANDLER command runtime in the embedded baseline" FORCE)
set(MYLITE_WITH_SELECT_INTO_FILE OFF CACHE BOOL "Disable SELECT INTO OUTFILE/DUMPFILE host-file writers in the embedded baseline" FORCE)
set(MYLITE_WITH_DISABLED_STARTUP_OPTIONS OFF CACHE BOOL "Disable startup options for disabled server subsystems in the embedded baseline" FORCE)
set(MYLITE_WITH_QUERY_LOGS OFF CACHE BOOL "Disable general and slow query log runtime in the embedded baseline" FORCE)
set(MYLITE_WITH_SQL_DIGEST OFF CACHE BOOL "Disable statement digest normalization in the embedded baseline" FORCE)
set(MYLITE_WITH_STATUS_VARIABLES OFF CACHE BOOL "Disable server status variable publication in the embedded baseline" FORCE)
set(MYLITE_WITH_STATEMENT_PROFILING_METADATA OFF CACHE BOOL "Disable statement profiling metadata in the embedded baseline" FORCE)
set(MYLITE_WITH_ORACLE_COMPAT_FUNCTIONS OFF CACHE BOOL "Disable Oracle compatibility function aliases in the embedded baseline" FORCE)
set(MYLITE_WITH_FULL_ERROR_MESSAGES OFF CACHE BOOL "Use compact server error messages in the embedded baseline" FORCE)
set(MYLITE_WITH_DYNAMIC_PLUGIN_LOADING OFF CACHE BOOL "Disable dynamic plugin shared-library loading in the embedded baseline" FORCE)
set(MYLITE_WITH_PROCEDURE_ANALYSE OFF CACHE BOOL "Disable PROCEDURE ANALYSE in the embedded baseline" FORCE)
set(MYLITE_WITH_SYSVAR_HELP_TEXT OFF CACHE BOOL "Disable system variable help text in the embedded baseline" FORCE)
set(MYLITE_WITH_STATIC_SHOW_INFO OFF CACHE BOOL "Disable static SHOW information in the embedded baseline" FORCE)
set(MYLITE_WITH_OPTION_HELP_TEXT OFF CACHE BOOL "Disable command-line option help text in the embedded baseline" FORCE)
set(MYLITE_WITH_OPTIMIZER_TRACE OFF CACHE BOOL "Disable optimizer trace diagnostics in the embedded baseline" FORCE)
set(MYLITE_WITH_PERSISTENT_STATISTICS OFF CACHE BOOL "Disable persistent optimizer statistics in the embedded baseline" FORCE)
set(MYLITE_WITH_PROCESSLIST_METADATA OFF CACHE BOOL "Disable process-list metadata in the embedded baseline" FORCE)
set(MYLITE_WITH_FOREIGN_SERVER_METADATA OFF CACHE BOOL "Disable mysql.servers metadata in the embedded baseline" FORCE)
set(MYLITE_WITH_BACKUP_RUNTIME OFF CACHE BOOL "Disable external backup runtime in the embedded baseline" FORCE)
set(MYLITE_WITH_VIO_TLS OFF CACHE BOOL "Disable VIO TLS transport in the embedded baseline" FORCE)
set(MYLITE_WITH_REPLICATION_EXEC_SYSVARS OFF CACHE BOOL "Disable replication execution system variables in the embedded baseline" FORCE)
set(MYLITE_WITH_REPLICATION_FILTERS OFF CACHE BOOL "Disable replication and binary-log filter runtime in the embedded baseline" FORCE)
set(MYLITE_WITH_RPL_TYPE_CONVERSION OFF CACHE BOOL "Disable row-replication type conversion in the embedded baseline" FORCE)
set(MYLITE_WITH_REPLICATION_HELPERS OFF CACHE BOOL "Disable residual replication helper objects in the embedded baseline" FORCE)
set(MYLITE_WITH_USERSTAT_DIAGNOSTICS OFF CACHE BOOL "Disable user statistics diagnostics in the embedded baseline" FORCE)
set(MYLITE_WITH_EVENT_PARSE_DATA OFF CACHE BOOL "Disable event scheduler parse-data validation in the embedded baseline" FORCE)
set(MYLITE_WITH_PROXY_PROTOCOL OFF CACHE BOOL "Disable PROXY protocol listener support in the embedded baseline" FORCE)
